# Generated by Django 4.2.6 on 2023-10-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
    ]
