# Generated by Django 4.2.6 on 2023-10-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_contato_complemento_alter_contato_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
